@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "br.com.fiap.auramed.infrastructure.main.AuramedApplication",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_98689 { 
   	label=com
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_660573057 { 
   	label=fiap
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AuramedApplication1735188782[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AuramedApplication</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   medicoRepository: MedicoRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ run(args: String...): int</TD></TR>
<TR><TD ALIGN="LEFT" >- testBuscarPorCrm()</TD></TR>
<TR><TD ALIGN="LEFT" >- testBuscarTodos()</TD></TR>
<TR><TD ALIGN="LEFT" >- testCreateMedico()</TD></TR>
<TR><TD ALIGN="LEFT" >- testCriarVariosMedicos()</TD></TR>
<TR><TD ALIGN="LEFT" >- testDesativarMedico()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Cpf392359058[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cpf</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   numero: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ numero(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DataNascimento392359058[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DataNascimento</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   data: LocalDate [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ data(): LocalDate</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DatabaseConnectionImpl2066118262[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DatabaseConnectionImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dataSource: DataSource [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Email392359058[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Email</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   enderecoEmail: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ enderecoEmail(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Endereco392359058[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Endereco</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bairro: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cep: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cidade: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   complemento: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logradouro: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numero: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   uf: UF [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ bairro(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ cep(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ cidade(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ complemento(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ logradouro(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ numero(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ uf(): UF</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

JdbcMedicoRepository2066118262[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JdbcMedicoRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   databaseConnection: DatabaseConnection [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ buscarPorCrm(crm: String): Optional&lt;Medico&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ buscarTodos(): List&lt;Medico&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ desativar(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >- mapResultSetToMedico(rs: ResultSet): Medico</TD></TR>
<TR><TD ALIGN="LEFT" >+ salvar(medico: Medico): Medico</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

NomeCompleto392359058[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NomeCompleto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   valor: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ valor(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Telefone392359058[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Telefone</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   numero: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ numero(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AuramedApplication1735188782 -> DataNascimento392359058[label="testBuscarPorCrm() -> data()"];
AuramedApplication1735188782 -> JdbcMedicoRepository2066118262[arrowhead=none];
AuramedApplication1735188782 -> Telefone392359058[label="testBuscarPorCrm() -> numero()"];
JdbcMedicoRepository2066118262 -> Cpf392359058[label="salvar() -> numero()"];
JdbcMedicoRepository2066118262 -> DataNascimento392359058[label="salvar() -> data()"];
JdbcMedicoRepository2066118262 -> DatabaseConnectionImpl2066118262[arrowhead=none];
JdbcMedicoRepository2066118262 -> Email392359058[label="salvar() -> enderecoEmail()"];
JdbcMedicoRepository2066118262 -> NomeCompleto392359058[label="salvar() -> valor()"];
JdbcMedicoRepository2066118262 -> Telefone392359058[label="salvar() -> numero()"];
    
}
@enduml